version: "3.3"

volumes:
  db-data:

networks: 
  instavote:
    driver: bridge

services: 
  vote:
    image: romsd/vote:master
    build: ./vote
    ports:
      - 5000:80
    depends_on: 
      - redis
    networks: 
      - instavote

  redis:
    image: redis:alpine
    networks: 
      - instavote

  db: 
    image: postgres:9.4
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust 
    volumes: 
      - "db-data:/var/lib/postgres/data"
    networks: 
      - instavote

  result: 
    image: romsd/result:master
    build: ./result
    ports:
      - 5001:4000
    depends_on: 
      - db
    networks: 
      - instavote

  worker: 
    image: romsd/worker:master
    build: ./result
    depends_on:
      - redis
      - db
    networks: 
      - instavote
